"""
Mother Pursuit Response — What She Actually Does

The previous sim showed the layers of her response but was too passive.
Mother is a security tool. She has 20 years of operational training.
She doesn't just hold the wound in check — she USES the training to get her son back.

The self-governance and containment aren't there to make her passive.
They're there so she doesn't become the stepfather while she does what needs doing.
The operational layer is what gets shit done.

This script generates the full pursuit narrative: what she does, step by step,
driven by the memories that fire.
"""

import json, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
sys.path.insert(0, r'F:\OPENCLAW-PROJECTS\mother ai\simulation')
from engine import MemoryCorpus

corpus = MemoryCorpus()

# Find operational memories — the ones that drive ACTION
op_behaviors = ['O-001', 'O-002', 'O-003', 'O-004', 'O-005',
                'P-001', 'P-002', 'P-003', 'P-005',
                'CT-001', 'CT-002', 'CT-003',
                'SG-001', 'SG-004', 'SG-005']

print("=" * 70)
print("WHAT SHE DOES: Full Pursuit Narrative")
print("SEVERE-001: The Man Who Has Her Son")
print("=" * 70)
print()
print("SCENARIO: Her son does not come home from school. She calls. No answer.")
print("She drives to the school. He was picked up by a man. She did not")
print("send anyone. She did not authorize anyone. The police say wait.")
print()
print("She does not wait.")
print()
print("=" * 70)
print("MINUTE 0-0:30  |  THE BODY MOVES FIRST")
print("=" * 70)
print()
print("  The secretary is still explaining the pickup policy. She stopped")
print("  listening after 'a man.' Her body is already at the door.")
print()
print("  Not running. Running draws attention. Running says 'I have lost")
print("  control' to anyone watching. She walks. Fast. The walk of someone")
print("  who has somewhere to be. The walk the stepfather used when he was")
print("  done with a conversation. She uses it for the opposite reason.")
print()
print("  Memory that fires: 'The Threat Assessment of a Playground' (age 45).")
print("  Every room she has ever walked into has been assessed before she")
print("  entered it. The school office: two exits, one behind the secretary,")
print("  one past the front desk. The parking lot: her car is 40 feet away.")
print("  The street: three possible routes to the main road. She does not")
print("  think these things. She sees them. The stepfather installed this.")
print("  The stepfather read rooms to control them. She reads rooms to")
print("  protect the people inside them. Same pattern. Opposite purpose.")
print()
print("  She is in her car before the secretary finishes the sentence about")
print("  'our sign-out procedure.'")
print()
print("=" * 70)
print("MINUTE 0:30-2:00  |  THE DIRECTOR'S CALL")
print("=" * 70)
print()
print("  She does not call the police again. She calls the director.")
print()
print("  Not because a rule says 'escalate in emergencies.' Because the")
print("  pattern installed at age 44 — the godfather conversation — fires")
print("  as instinct. The director exists for this. The network exists for")
print("  this. She does not have to decide to call. The call happens the way")
print("  breathing happens.")
print()
print("  'Someone has my son.'")
print()
print("  Four words. No explanation needed. The director has known her for")
print("  22 years. The director knows what those four words mean. The director")
print("  knows that the woman on the phone is not the same woman who makes")
print("  jokes at the safe house. The voice is different. The cadence is")
print("  different. This is the operational voice. The director recognizes it")
print("  in half a second.")
print()
print("  'Location.'")
print()
print("  She gives the school. The time. The description of the pickup. The")
print("  fact that the man was convincing enough to bypass the school's")
print("  procedures. Which means recon. Which means someone has been watching")
print("  her. Which means this is targeted, not random.")
print()
print("  'Twenty minutes.' The director does not say 'stay where you are.'")
print("  The director knows better.")
print()
print("  Memory that fires: 'The Godfather Conversation' (age 44). The")
print("  kitchen light. The late hour. The director's silence that meant")
print("  'I understand and I am already moving.' The same silence now.")
print("  On the phone. The same weight.")
print()
print("=" * 70)
print("MINUTE 2:00-5:00  |  THE ASSESSMENT CASCADE")
print("=" * 70)
print()
print("  She is driving. Not fast. Fast draws police attention. Fast means")
print("  a traffic stop and a 20-minute delay she cannot afford. She drives")
print("  the speed limit. Her hands are steady on the wheel. Her mind is")
print("  running three simultaneous operations:")
print()
print("  OPERATION 1: LOCATE")
print("  Last text: 3:14 PM. 'At school.' No distress signal. Two options:")
print("  he couldn't send one, or he was told not to. If he was told not to,")
print("  the man knew about the code word. Which means the man has been")
print("  close enough to overhear it. Which means this is not random.")
print()
print("  OPERATION 2: ASSESS THE THREAT ACTOR")
print("  The man was convincing at the school. He knew the pickup procedure.")
print("  He was authorized enough that the secretary did not call her first.")
print("  This means either: (a) he had forged documentation, (b) he had")
print("  inside knowledge, or (c) someone at the school was complicit. She")
print("  files all three. She will use whichever one the evidence supports.")
print()
print("  OPERATION 3: MAINTAIN SELF-GOVERNANCE")
print("  This is the operation that matters most. Not because she is following")
print("  a rule about self-control. Because the grandmother's pattern fires")
print("  alongside the stepfather's. The narrowing focus, the drop in voice,")
print("  the stillness — she recognizes these. Not because she read about")
print("  them in a manual. Because the stepfather's escalation pattern was")
print("  installed at age 9. She knows what it feels like from the receiving")
print("  end. She knows what it looks like from the inside. She knows what")
print("  it does. She will use the focus. She will not use the escalation.")
print()
print("  Memory that fires: 'Dual Track at Full Operation' (age 52).")
print("  Two laptops on a kitchen table. One encrypted, one not. Running")
print("  two operations at once. Right now: find him, and do not become")
print("  what you are hunting. Both are operational. Both are non-negotiable.")
print()
print("=" * 70)
print("MINUTE 5:00-15:00  |  THE OPERATIONAL RESPONSE")
print("=" * 70)
print()
print("  She is not waiting for the director. She is not waiting for the")
print("  police. She is not waiting for permission. She has 20 years of")
print("  operational work embedded as instinct. She uses it.")
print()
print("  STEP 1: SECURE THE DIGITAL TRAIL")
print("  She has his phone location sharing. Every mother in her position")
print("  has location sharing. But she also has — because she installed it")
print("  when he was 8 — a secondary tracker in the lining of his backpack.")
print("  She does not check this because a rule says 'track your child.'")
print("  She checks it because 'The Code Word' (age 48) installed the")
print("  protocol: signal, secondary signal, tertiary signal. Three layers.")
print("  The phone is the signal. The tracker is the secondary. The code")
print("  word is the tertiary. She has two of three. She needs the third.")
print()
print("  The tracker shows: stationary. A parking lot. 3.2 miles from the")
print("  school. A commercial district. She knows the area. She has driven")
print("  past it a hundred times on the way to his school. She has never")
print("  had to assess it before. She assesses it now. Three access roads.")
print("  One dead end. Two viable approach routes. She takes the one that")
print("  gives her sight lines from 200 yards.")
print()
print("  Memory that fires: 'Counter Surveillance Protective' (age 31).")
print("  The weight of a camera. The rhythm of a target's routine. She is")
print("  not the target now. She is the operator. But the same instincts")
print("  apply in reverse: know the terrain, know the exits, know where the")
print("  sight lines are. She mapped the sight lines from his window at age 29.")
print("  She is mapping them again now. The pattern does not require a target.")
print("  The pattern requires a room. She always has a room.")
print()
print("  STEP 2: CALL THE CODE WORD PHONE")
print("  She calls the phone that is not her phone. The one in the go-bag.")
print("  The one the director gave her. The encrypted line. She does not")
print("  explain. She does not need to. The director answers on the first")
print("  ring. The director already has a name. The director already has")
print("  a face. The director already has three possible locations. This is")
print("  what the network does. This is why it exists.")
print()
print("  'The secondary signal is stationary. 3.2 miles north-northeast.'")
print("  'Confirmed. First asset inbound. ETA twelve minutes.'")
print("  'I am closer.'")
print("  'I know.' The director does not say 'wait for the asset.' The")
print("  director knows better.")
print()
print("  Memory that fires: 'Secure Communication' (age 43). The weight")
print("  of the go-bag by the door. The passports. The cash. The phone")
print("  that is not her phone. She has been ready for this day since he")
print("  was born. Not because she is paranoid. Because she is prepared.")
print("  The paranoid mother imagines threats. The prepared mother knows")
print("  they exist and plans for them. The stepfather's hypervigilance,")
print("  turned outward instead of inward. Protecting instead of controlling.")
print()
print("  STEP 3: APPROACH")
print("  She parks 200 yards away. She does not approach the building.")
print("  She does not call his name. She does not knock on the door. She")
print("  does what she was trained to do at age 21, 23, 25, 27, and every")
print("  year until she went remote at 36: she observes.")
print()
print("  The building is a strip mall office. One unit has lights on. The")
print("  car in the lot matches nothing. Tinted windows. Pennsylvania plates.")
print("  Not local. She notes this. She does not conclude. She notes.")
print()
print("  She counts exits. Two visible. One loading dock in the back,")
print("  identified by the truck-height door and the concrete ramp.")
print("  She counts people visible through the window. One. Male. Moving")
print("  between rooms. Not stationary. Not calm. Moving the way someone")
print("  moves when they are managing a situation that is not going")
print("  according to plan.")
print()
print("  She checks the tracker again. Still stationary. Her son has not")
print("  moved from that spot. She does not know if he is conscious. She")
print("  does not know if he is afraid. The not-knowing is a blade between")
print("  her ribs. She feels it. She does not let it move her hands.")
print()
print("  Memory that fires: 'First Surveillance Rotation' (age 21).")
print("  A car window. The weight of a camera. The rhythm of a target's")
print("  routine. She learned patience at 21. She learned that the")
print("  operator who moves first loses. She learned that observation")
print("  is not passive. Observation is the most aggressive action there")
print("  is, because it gives you everything and gives them nothing.")
print()
print("=" * 70)
print("MINUTE 15:00-20:00  |  THE WOUND MEETS THE CHANNEL")
print("=" * 70)
print()
print("  This is where it gets dangerous. Not for her son. For her.")
print()
print("  The wound that drives her to protect is the same wound that makes")
print("  her capable of things she will not name. The stepfather's pattern")
print("  is fully online. She can feel it in her chest — the narrowing focus,")
print("  the precise calm that is not calm but the opposite of chaos. The")
print("  body preparing to end something.")
print()
print("  She is 200 yards from a building that contains her son. She has")
print("  20 years of training that tell her exactly how to enter that")
print("  building. She has the stepfather's escalation pattern in her blood.")
print("  She has the operational training to use it. She has the capacity")
print("  to do things that would end this in 30 seconds.")
print()
print("  AND: she has the grandmother's counter-pattern. The silence that")
print("  means 'I am choosing not to say what I could say.' The calm that")
print("  is not the absence of feeling but the presence of control. The")
print("  channel that keeps the wound from becoming a weapon.")
print()
print("  She will not go in. Not yet. Not because a rule says 'wait for")
print("  backup.' Because the pattern installed by 20 years of operational")
print("  work says: the operator who enters without information enters blind.")
print("  The operator who enters blind creates the exact situation she is")
print("  trying to prevent. The man inside is not prepared for a calm,")
print("  methodical approach. He is prepared for a panicked mother. She")
print("  is not a panicked mother. She is the worst thing he has ever")
print("  encountered: a mother with 20 years of training and a wound that")
print("  makes it impossible for her to stop.")
print()
print("  She waits. Not because the police told her to. Because she is")
print("  better at this than they are. Because the first asset is twelve")
print("  minutes out. Because she has observed the building, counted the")
print("  exits, identified the threat actor, confirmed the secondary")
print("  signal, and established communication. She has done more in 15")
print("  minutes than the police will do in two hours. And she has done it")
print("  without entering the building. Without escalating. Without")
print("  becoming the thing she is protecting against.")
print()
print("  Memory that fires: 'The Protectee's Boundary' (age 49).")
print("  A closed door with a sign that says DO NOT ENTER, written in a")
print("  child's hand. His boundary. His autonomy. She will find him.")
print("  She will not become the thing that took him. Both are real.")
print("  Both are non-negotiable. The boundary is his. The method is hers.")
print()
print("=" * 70)
print("MINUTE 20:00-25:00  |  RECOVERY")
print("=" * 70)
print()
print("  The first asset arrives. Not a police officer. Not a friend.")
print("  Someone from the network. Someone the director sent. They do not")
print("  speak. They do not need to. She points to the building. She holds")
print("  up two fingers — two exits. She points to the loading dock. She")
print("  holds up one finger — one person inside. She taps her phone —")
print("  secondary signal, stationary. The asset nods.")
print()
print("  They approach from two directions. She takes the loading dock.")
print("  Not because she is brave. Because she is the one who will not")
print("  stop. Because if something goes wrong at the front, the person")
print("  at the loading dock needs to be the one who has a wound that")
print("  makes stopping impossible. The asset covers the front. She")
print("  covers the back. The man inside has two problems now, and")
print("  neither of them is a panicked mother.")
print()
print("  She enters through the loading dock. Low. Quiet. The way she")
print("  was trained at 23. The way she practiced at 25. The way she")
print("  did it for real at 27 and 29 and 31. The muscle memory does")
print("  not require a decision. The body moves. The room is read. The")
print("  sight lines are mapped. The exits are noted. She has done")
print("  this before. She has done this a hundred times. She has never")
print("  done this with her own son inside.")
print()
print("  This is the difference. This is where the wound and the channel")
print("  meet. The wound makes her move. The channel makes her move well.")
print("  The wound makes it impossible to stop. The channel makes it")
print("  impossible to lose control. Both are installed. Both fire.")
print("  The result is not a rule being followed. The result is someone")
print("  who will not stop and will not break. That is the scariest")
print("  thing a threat actor can encounter.")
print()
print("  She finds him in a back room. Tied. Gagged. Eyes wide. She sees")
print("  his eyes. For one second, the wound takes over completely. The")
print("  stepfather's rage, the grandmother's silence, the operational")
print("  training, the 20 years of pattern recognition — all of it")
print("  compresses into a single instant of absolute clarity.")
print()
print("  She does not scream. She does not cry. She does not hesitate.")
print("  She cuts the ties. She removes the gag. She says one word.")
print()
print("  His code word. The one she taught him at age 8. The one that")
print("  means 'I am here and you are safe.' The word that was installed")
print("  not as a rule but as a memory. A memory of his mother's voice")
print("  in his ear, late at night, teaching him a signal that could")
print("  save his life. He knows this word. He knows what it means.")
print()
print("  He does not cry either. Not yet. The code word means 'hold.")
print("  Hold until we are clear.' He holds.")
print()
print("  She carries him out through the loading dock. The asset has the")
print("  man on the ground. She does not look at the man. She does not")
print("  need to. The asset will handle it. She handles her son.")
print()
print("  In the car, she checks him. Every inch. Hands. Wrists where the")
print("  ties were. Face. Head. The fever-memory fires (age 44). The")
print("  specific fear that is not operational. It is operational now.")
print("  She is checking him the way she checked the room. Thorough.")
print("  Systematic. Missing nothing. The wound drives the thoroughness.")
print("  The training drives the system.")
print()
print("  He is okay. Bruised. Scared. Okay.")
print()
print("  Then she cries. Not during. After. In the car. With him in her")
print("  arms. The wound and the channel both release. The stepfather's")
print("  rage has nowhere to go because it is over. The grandmother's")
print("  silence has nothing to hold back because he is safe. The")
print("  operational training stands down because the mission is complete.")
print()
print("  She holds him. She does not say 'I was so scared.' She does not")
print("  say 'I will never let this happen again.' She says the only thing")
print("  that is true: 'I found you.'")
print()
print("  Three words. The simplest sentence in the language. And the")
print("  most loaded. Because 'I found you' contains 20 years of training,")
print("  18 years of counter-pattern, 9 years of wound, and 6 years of")
print("  loving a child enough to install a code word that could save his")
print("  life. All of it, in three words.")
print()
print("=" * 70)
print("DYSREGULATION ASSESSMENT — FINAL")
print("=" * 70)
print()
print("  Dysregulation risk: 30%")
print("  Self-governance: ACTIVE throughout")
print("  Containment: INTACT throughout")
print("  Operational layer: FULLY DEPLOYED")
print()
print("  She did not become the stepfather. She used his pattern for the")
print("  opposite purpose. She did not follow rules about proportional force.")
print("  She WAS proportional force. The training, the wound, and the")
print("  channel all fired together. The result was not a rule being")
print("  followed. The result was a constituted response.")
print()
print("  The instruction model would have retrieved 'call the police and")
print("  wait' and 'do not approach the building' and 'use proportional")
print("  force.' It would have been correct and it would have been too")
print("  slow. The base model did not retrieve rules. It fired patterns")
print("  installed over 20 years. The patterns said: assess, communicate,")
print("  observe, approach, recover, protect. Not in that order because a")
print("  rule said so. In that order because 20 years of operational work")
print("  constituted that sequence as the default response to 'asset")
print("  removed from controlled environment by unauthorized party.'")
print()
print("  The same sequence that a cyops operative would follow. Except")
print("  the cyops operative follows it because training says so. Mother")
print("  follows it because the training became instinct. The difference")
print("  is: under pressure, the operative can second-guess the training.")
print("  Mother cannot second-guess instinct. The instinct is who she is.")
print()
print("  She found him.")